name: Sarah Anderson
favicon: null
layout_spectrum: 0.5693561194930226
typography_spectrum: 0.8205569693818688
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.19024191703647375
  lightness: 0.3257699739187956
  saturation: 0.6634719506837428
  rhythmicContrast: 0.630756571656093
purpose: []
